package net.sunniwell.vms.mapper;

import java.util.List;
import net.sunniwell.vms.model.ScanTaskModel;

public interface ScanTaskModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_task
     *
     * @mbg.generated
     */
    int insert(ScanTaskModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_task
     *
     * @mbg.generated
     */
    List<ScanTaskModel> selectAll();
}