package net.sunniwell.vms.mapper;

import java.util.List;
import net.sunniwell.vms.model.SubtitleModel;

public interface SubtitleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtitle
     *
     * @mbg.generated
     */
    int insert(SubtitleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtitle
     *
     * @mbg.generated
     */
    List<SubtitleModel> selectAll();
}