package net.sunniwell.vms.mapper;

import java.util.List;
import net.sunniwell.vms.model.VideoModel;

public interface VideoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    int insert(VideoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    List<VideoModel> selectAll();
}