package net.sunniwell.vms.model;

public class ScanTaskModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.media_id
     *
     * @mbg.generated
     */
    private String mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.media_name
     *
     * @mbg.generated
     */
    private String mediaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.error_detail
     *
     * @mbg.generated
     */
    private String errorDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.create_utc
     *
     * @mbg.generated
     */
    private Long createUtc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.report_utc
     *
     * @mbg.generated
     */
    private Long reportUtc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_task.media_data
     *
     * @mbg.generated
     */
    private String mediaData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.id
     *
     * @return the value of scan_task.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.id
     *
     * @param id the value for scan_task.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.media_id
     *
     * @return the value of scan_task.media_id
     *
     * @mbg.generated
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.media_id
     *
     * @param mediaId the value for scan_task.media_id
     *
     * @mbg.generated
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId == null ? null : mediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.media_name
     *
     * @return the value of scan_task.media_name
     *
     * @mbg.generated
     */
    public String getMediaName() {
        return mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.media_name
     *
     * @param mediaName the value for scan_task.media_name
     *
     * @mbg.generated
     */
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName == null ? null : mediaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.status
     *
     * @return the value of scan_task.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.status
     *
     * @param status the value for scan_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.error_detail
     *
     * @return the value of scan_task.error_detail
     *
     * @mbg.generated
     */
    public String getErrorDetail() {
        return errorDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.error_detail
     *
     * @param errorDetail the value for scan_task.error_detail
     *
     * @mbg.generated
     */
    public void setErrorDetail(String errorDetail) {
        this.errorDetail = errorDetail == null ? null : errorDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.create_utc
     *
     * @return the value of scan_task.create_utc
     *
     * @mbg.generated
     */
    public Long getCreateUtc() {
        return createUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.create_utc
     *
     * @param createUtc the value for scan_task.create_utc
     *
     * @mbg.generated
     */
    public void setCreateUtc(Long createUtc) {
        this.createUtc = createUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.report_utc
     *
     * @return the value of scan_task.report_utc
     *
     * @mbg.generated
     */
    public Long getReportUtc() {
        return reportUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.report_utc
     *
     * @param reportUtc the value for scan_task.report_utc
     *
     * @mbg.generated
     */
    public void setReportUtc(Long reportUtc) {
        this.reportUtc = reportUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_task.media_data
     *
     * @return the value of scan_task.media_data
     *
     * @mbg.generated
     */
    public String getMediaData() {
        return mediaData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_task.media_data
     *
     * @param mediaData the value for scan_task.media_data
     *
     * @mbg.generated
     */
    public void setMediaData(String mediaData) {
        this.mediaData = mediaData == null ? null : mediaData.trim();
    }
}