package net.sunniwell.vms.model;

public class SubtitleModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.media_id
     *
     * @mbg.generated
     */
    private String mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.media_name
     *
     * @mbg.generated
     */
    private String mediaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.serial
     *
     * @mbg.generated
     */
    private Integer serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtitle.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.id
     *
     * @return the value of subtitle.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.id
     *
     * @param id the value for subtitle.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.media_id
     *
     * @return the value of subtitle.media_id
     *
     * @mbg.generated
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.media_id
     *
     * @param mediaId the value for subtitle.media_id
     *
     * @mbg.generated
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId == null ? null : mediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.media_name
     *
     * @return the value of subtitle.media_name
     *
     * @mbg.generated
     */
    public String getMediaName() {
        return mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.media_name
     *
     * @param mediaName the value for subtitle.media_name
     *
     * @mbg.generated
     */
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName == null ? null : mediaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.serial
     *
     * @return the value of subtitle.serial
     *
     * @mbg.generated
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.serial
     *
     * @param serial the value for subtitle.serial
     *
     * @mbg.generated
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.language
     *
     * @return the value of subtitle.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.language
     *
     * @param language the value for subtitle.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtitle.file_path
     *
     * @return the value of subtitle.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtitle.file_path
     *
     * @param filePath the value for subtitle.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}